"""add resource chunks

Revision ID: 4848f4cd1af6
Revises: 560e41f7285a
Create Date: 2026-08-17 11:09:19.973276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4848f4cd1af6'
down_revision: Union[str, Sequence[str], None] = '560e41f7285a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_chunks_id'), 'resource_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_resource_chunks_page_number'), 'resource_chunks', ['page_number'], unique=False)
    op.create_index(op.f('ix_resource_chunks_resource_id'), 'resource_chunks', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_chunks_resource_id'), table_name='resource_chunks')
    op.drop_index(op.f('ix_resource_chunks_page_number'), table_name='resource_chunks')
    op.drop_index(op.f('ix_resource_chunks_id'), table_name='resource_chunks')
    op.drop_table('resource_chunks')
    # ### end Alembic commands ###
